# Use trusty for better performance (and avoiding mysql/postgres/solr gone issues on precise and container infra)
dist: trusty
sudo: required

language: php

services:
  - mysql
  - postgresql

# Mysql isn't installed on trusty (only client is), so we need to specifically install it
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

matrix:
  # mark as finished before allow_failures are run
  fast_finish: true
  include:
# 7.0 (7 with unit & sqlite integration first to fail early with fast_finish)
    - php: 7.0
      env: TEST_CONFIG="phpunit.xml"
    - php: 7.0
      env: TEST_CONFIG="phpunit-integration-legacy.xml"
#    - php: 7.0
#      env: REST_TEST_CONFIG="phpunit-functional-rest.xml"
#    - php: 7.0
#      env: BEHAT_OPTS="--profile=rest --suite=fullJson"
    - php: 7.0
      env: SOLR_VERSION="4.10.4" TEST_CONFIG="phpunit-integration-legacy-solr.xml" CORES_SETUP="single" SOLR_CONFS="vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/schema.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/custom-fields-types.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/language-fieldtypes.xml"
# 5.6
    - php: 5.6
      env: TEST_CONFIG="phpunit.xml"
    - php: 5.6
      env: TEST_CONFIG="phpunit-integration-legacy.xml" DB="postgresql" DATABASE="pgsql://postgres@localhost/testdb"
    - php: 5.6
      env: ELASTICSEARCH_VERSION="1.4.2" TEST_CONFIG="phpunit-integration-legacy-elasticsearch.xml"
# 5.5
    - php: 5.5
      env: TEST_CONFIG="phpunit.xml" SYMFONY_VERSION="~2.8.0"
    - php: 5.5
      env: TEST_CONFIG="phpunit-integration-legacy.xml" DB="mysql" DATABASE="mysql://root@localhost/testdb" SYMFONY_VERSION="~2.8.0"
#    - php: 5.6
#      env: BEHAT_OPTS="--profile=core --tags=~@broken"
# hhvm - disabled, no need to enable before travis has newer versions avaiable
#    - php: hhvm
#      env: TEST_CONFIG="phpunit.xml"


# test only master (+ Pull requests)
branches:
  only:
    - master
    - "6.1"
    - "6.2"

# setup requirements for running unit/integration/behat tests
before_script:
  # Prepare system
  - if [ "$TEST_CONFIG" != "" ] ; then ./bin/.travis/prepare_unittest.sh ; fi
  - if [ "$BEHAT_OPTS" != "" ] ; then ./bin/.travis/prepare_behat.sh ; fi
  - if [ "$REST_TEST_CONFIG" != "" ] ; then ./bin/.travis/prepare_behat.sh ; echo pwd; cd "$HOME/build/ezplatform/vendor/ezsystems/ezpublish-kernel"; ./bin/.travis/prepare_rest_functional_tests.sh; fi
  # Detecting timezone issues by testing on random timezone
  - TEST_TIMEZONES=("America/New_York" "Asia/Calcutta" "UTC")
  - TEST_TIMEZONE=${TEST_TIMEZONES["`shuf -i 0-2 -n 1`"]}

# execute phpunit or behat as the script command
script:
  - if [ "$TEST_CONFIG" != "" ] ; then php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 vendor/bin/phpunit -c $TEST_CONFIG ; fi
  - if [ "$BEHAT_OPTS" != "" ] ; then cd "$HOME/build/ezplatform" && php bin/behat -vv $BEHAT_OPTS ; fi
  - if [ "$REST_TEST_CONFIG" != "" ] ; then cd "$HOME/build/ezplatform"; php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 bin/phpunit -v vendor/ezsystems/ezpublish-kernel/eZ/Bundle/EzPublishRestBundle/Tests/Functional ; fi

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
